name: Deploy to Cloudflare Pages
on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
  deploy:
    needs: build
    runs-on: docker
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy to Cloudflare Pages
        uses: https://github.com/cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy dist
            --project-name nfason-com
            --branch {{ forgejo.ref_name }}
            --commit-hash {{ forgejo.sha }}
