name: Deploy to Cloudflare Pages
on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies and build
        uses: actions/setup-node@v3
        with:
          node-version: 18
        runs:
          - npm install
          - npm run build
      - name: Upload build artifacts
        with:
          name: build
          path: dist
  deploy:
    needs: build
    runs-on: docker
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy dist \
            --project-name nfason-com \
            --branch {{ forgejo.ref_name }} \
            --commit-hash {{ forgejo.sha }}
